# Generated by Django 6.0.3 on 2026-03-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_base', to='empresas.rubro')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.DurationField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='empresas.empresa')),
                ('servicio_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_empresa', to='servicios.serviciobase')),
            ],
        ),
    ]
