# Generated by Django 6.0.3 on 2026-03-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_suscripcion_fecha_vencimiento_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='limite_simultaneo',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad maxima de turnos simultaneos. Vacio = sin limite.', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio_anual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='periodicidad',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=20),
        ),
    ]
