# Generated by Django 6.0.3 on 2026-03-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=30, unique=True)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='geo.localidad')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='geo.pais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='geo.provincia')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='empresas.rubro')),
            ],
        ),
    ]
